/* Generated by split_replay_voice.py -- do not edit by hand. */
#ifndef REPLAY_VOICE_H
#define REPLAY_VOICE_H

#define REPLAY_CLIP_COUNT  6
#define REPLAY_MAX_PIECES  3
#define REPLAY_SAMPLE_RATE 22050

/* The pieces of the loaded clip occupy consecutive SFX slots starting
 * at the original announcer slot, so piece i lives in slot FIRST + i.
 * Everything in this range is exempt from g_masterVolume attenuation. */
#define REPLAY_VOICE_SLOT_FIRST 0x38
#define REPLAY_VOICE_SLOT_LAST  (REPLAY_VOICE_SLOT_FIRST + REPLAY_MAX_PIECES - 1)
#define REPLAY_VOICE_SLOT(i)    (REPLAY_VOICE_SLOT_FIRST + (i))
#define IS_REPLAY_VOICE_SLOT(s) \
    ((s) >= REPLAY_VOICE_SLOT_FIRST && (s) <= REPLAY_VOICE_SLOT_LAST)

typedef struct {
    const char   *pieceName[REPLAY_MAX_PIECES]; /* no extension */
    unsigned int  pieceSamples[REPLAY_MAX_PIECES];
    unsigned char pieceCount;
    unsigned int  totalSamples;                 /* sum of pieces */
    unsigned int  durationMs;                   /* duck this long */
} ReplayClipInfo;

/* Only the sequencer needs the table itself; everyone else includes this
 * header for the slot macros, so keep the definition out of their TUs. */
#ifdef REPLAY_VOICE_TABLE
static const ReplayClipInfo g_replayClipInfo[REPLAY_CLIP_COUNT] = {
    { { "REPLAY1A", "REPLAY1B", 0 }, { 48129, 63678, 0 }, 2, 111807, 5071 },
    { { "REPLAY2A", "REPLAY2B", 0 }, { 50311, 20782, 0 }, 2, 71093, 3224 },
    { { "REPLAY3A", "REPLAY3B", 0 }, { 64139, 45480, 0 }, 2, 109619, 4971 },
    { { "REPLAY4A", "REPLAY4B", "REPLAY4C" }, { 64005, 58875, 29235 }, 3, 152115, 6899 },
    { { "REPLAY5A", "REPLAY5B", 0 }, { 50560, 32246, 0 }, 2, 82806, 3755 },
    { { "REPLAY6A", "REPLAY6B", 0 }, { 21888, 52939, 0 }, 2, 74827, 3394 },
};
#endif /* REPLAY_VOICE_TABLE */

#endif /* REPLAY_VOICE_H */
